package gormx

const (
	FieldEvent                = "event"
	FieldDBSystem             = "db.system"
	FieldDBStatement          = "db.statement"
	FieldDBFingerprint        = "db.fingerprint"
	FieldDBQueryType          = "db.query_type"
	FieldDBTable              = "db.table"
	FieldDBStatementTruncated = "db.statement_truncated"
	FieldDBRows               = "db.rows_affected"
	FieldDBResultStatus       = "db.result_status"
	FieldDBWhereColumns       = "db.where.columns"
	FieldDBWhereValues        = "db.where.values"
	FieldDBWhereConditions    = "db.where.conditions"
	FieldDurationMS           = "duration_ms"
	FieldCorrelation          = "correlation_id"
	FieldLayer                = "layer"
	FieldComponent            = "component"
	FieldOperation            = "operation"
	FieldErrorKind            = "error.kind"
	FieldErrorMessage         = "error.message"
	FieldErrorExpected        = "error.expected"
	FieldErrorActual          = "error.actual"
)
